platform:ios,'9.0'
target "MoenProject" do

#AFNetworking
pod 'AFNetworking','~>3.2.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'MBProgressHUD','~> 1.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'YYModel','~> 1.0.4'
pod 'MJRefresh', '~> 3.1.12'
pod 'IQKeyboardManager'

#add by wxy
pod 'MJExtension', '3.1.2'
pod 'SDAutoLayout'
#pod 'MyLayout'
pod 'ReactiveObjC'
pod 'UITableView+FDTemplateLayoutCell'
pod 'RadioButton'
#pod 'SKSTableView', '~> 0.0.3'

pod 'TZImagePickerController'
end
